### ISSUE TITLE
Webrtc not working on chrome without disabling chrome flags.

### ISSUE THREAD

**Issue by jaskarn-s-kalsi** [centricular/gstwebrtc-demos#223] opened 2020-11-02 02:55 UTC
Hi we are trying to stream to chrome using webrtcbin.
We can stream to edge on the local network. but stream doesnot play on chrome, or firefox.
Thing is we donot want to set any flags on the chrome.
What we need to setup for webrtcbin to stream to these browsers.
Our stream only stays on local LAN.
I know chrome now sends .local as ip's. i am resolving them before setting ice. as libnice will not resolve this.
We are using unsecure websocket for signalling server.

Pipeline: decklink -> nvh264enc -> rtph264pay -> webrtcbin
Gstreamer version 1.16.2
ubuntu 20
python 3.8
Thanks.

**Comment by ystreet** [comment] 2020-11-02 07:46
Duplicate of https://gitlab.freedesktop.org/gstreamer/gst-plugins-bad/-/issues/1445

**Closed as completed by ystreet** 2020-11-02 07:46 UTC
