### ISSUE TITLE
Example code of how to force keyframe with GstForceKeyUnit?

### ISSUE THREAD

**Issue by robert-m-taylor** [centricular/gstwebrtc-demos#186] opened 2020-05-05 20:46 UTC
The problem persists that the video stream from browser back to sendrecv demo is corrupted when network packet loss occurs.  The previously identified solution to this problem of forcing keyframes to be sent was given by Matthew Waters below.  However, I'm having trouble implementing this approach.  Could you provide a sample code snippet that's compatible with webrtc-sendrecv.c or webrtc-sendrecv.py that implements this suggested solution?  This would go a long way to making this demo workable.

------------------------------------------------------------------------------------------------------------------
One can force a keyframe by sending a GstForceKeyUnit request upstream on the src pad of the video stream output by webrtcbin.  This is converted internally by GStreamer's rtp implementation into a fir/pli rtcp message that is sent to the peer: https://gitlab.freedesktop.org/gstreamer/gst-plugins-good/blob/master/gst/rtpmanager/rtpsession.c#L4435 .

https://gstreamer.freedesktop.org/documentation/design/keyframe-force.html#upstream

_Originally posted by @ystreet in https://github.com/centricular/gstwebrtc-demos/issues/61#issuecomment-438915464_

**Comment by alexlapa** [comment] 2020-05-06 12:34
Does gstreamer's SDP offer contain? `rtcp-fb` lines? e.g.:

```
a=rtcp-fb:96 goog-remb
a=rtcp-fb:96 transport-cc
a=rtcp-fb:96 ccm fir
a=rtcp-fb:96 nack
a=rtcp-fb:96 nack pli
```

Congestion control is a really important part of WebRTC, and i would expect that `webrtcbin` provides it "out of the box". Otherwise, it is not really usable outside corporate networks.

**Comment by robert-m-taylor** [comment] 2020-05-06 20:31
Yes.   Below is my sending offer.  The received answer also has the "a=rtcp-fb:96 nack pli" line.  I did notice the performance is much better if I vpn into my corporate network and run the same demo.  I guess less packet loss that way.  I did set up and am using my own TURN server using Coturn as described [here](https://ourcodeworld.com/articles/read/1175/how-to-create-and-configure-your-own-stun-turn-server-with-coturn-in-ubuntu-18-04).  I'm not sure if that makes any difference.

It seems like something like the following lines should be triggered inside a conditional block in the "on_incoming_stream" function in webrtc-sendrecv.py but I'm not sure:
 
s = Gst.Structure("GstForceKeyUnit")
s.set_value('timestamp', timestamp, 'uint64')
s.set_value('stream-time', timestamp, 'uint64')
s.set_value('running-time', running_time, 'uint64')
s.set_value('all-headers', True)
pad.push_event(Gst.Event.new_custom(Gst.EventType.CUSTOM_DOWNSTREAM,s))

------------------------------------------------------
Sending offer:
v=0
o=- 4814920190397648158 0 IN IP4 0.0.0.0
s=-
t=0 0
a=ice-options:trickle
a=msid-semantic:WMS sendrecv
m=video 9 UDP/TLS/RTP/SAVPF 96
c=IN IP4 0.0.0.0
a=setup:actpass
a=ice-ufrag:IJzec+HLQlYoOP2GQFaG2MtdSWxKIjfj
a=ice-pwd:8LmS7WrSIAMjhNYlIVWZg/+ZxxT8l3nd
a=sendrecv
a=rtcp-mux
a=rtcp-rsize
a=rtpmap:96 VP8/90000
a=rtcp-fb:96 nack pli
a=framerate:30
a=ssrc:2550752610 msid:user2509883025@host-55dfee6e webrtctransceiver0
a=ssrc:2550752610 cname:user2509883025@host-55dfee6e
a=mid:video0
a=fingerprint:sha-256 BE:56:80:74:42:02:A5:17:73:71:63:BF:13:5D:E7:31:04:91:74:D4:8C:90:09:3C:C3:F4:44:7F:3E:D8:09:DF

**Comment by sampleref** [comment] 2020-05-07 11:29
I do want to send a GstForceKeyUnit to upstream only if I receive a PLI from downstream webrtc viewers instead of time interval like every 10 secs


I have a setup as below:

**Chrome-A(webrtc)(Sender) ->=Network=> Gstreamer(webrtcbin-A)->rtpvp8depay->tee->rtpvp8pay->webrtcbin-B->=Network=> Chrome-B(webrtc)(Reciever)**

Now the Chrome-B sends a PLI request as below, I verified it from Wireshark:

> ...0 0001 = RTCP Feedback message type (FMT): Picture Loss Indication (1)
>     Packet type: Payload-specific Feedback (206)

Currently I am triggering below KeyFrame request(send_key_frame_request_to_sender) every 10 secs or at some defined interval:

```
void send_key_frame_request_to_sender() {
GstPad *videosrcpad;
        videosrcpad = gst_element_get_static_pad(webrtcbin-A, "videosrcpad");
        gst_pad_send_event(videosrcpad, gst_event_new_custom(GST_EVENT_CUSTOM_UPSTREAM,
                                                                 gst_structure_new("GstForceKeyUnit", "all-headers",
                                                                                   G_TYPE_BOOLEAN, TRUE, NULL)));
}

```

**But I really want trigger the above(send_key_frame_request_to_sender) only when Chrome-B(webrtc)  RTCP Feedback message type (FMT): Picture Loss Indication (1) is received** **or even FIR request**

I tried to fetch the RTCP-PSFB-PLI as below from webrtcbin-B:

```
rtpbin = gst_bin_get_by_name(GST_BIN(webrtcbin-B), "rtpbin");
        if (rtpbin) {
            g_signal_connect (rtpbin, "on-new-ssrc", G_CALLBACK(on_new_ssrc_callback_receiver), webRtcPeerPtr.get());
            g_object_unref(rtpbin);
        }

void on_new_ssrc_callback_receiver(GstElement *rtpbin, guint session, guint ssrc, gpointer udata) {
   GstPad *rtcp_sink_pad;
    gchar *padName;
    padName = g_strdup_printf("recv_rtcp_sink_%u", session);
    rtcp_sink_pad = gst_element_get_static_pad(rtpbin, padName);
    if (rtcp_sink_pad) {
        GST_INFO("Pad Already Exists with name %s ", padName);
    } else {
        rtcp_sink_pad = gst_element_get_request_pad(rtpbin, padName);
    }
    g_free(padName);
    if (rtcp_sink_pad) {
        gst_pad_add_probe(rtcp_sink_pad, GST_PAD_PROBE_TYPE_BUFFER, (GstPadProbeCallback) 
          rtcp_sink_buffer_pad_probe_cb,
                          NULL, NULL);
        gst_object_unref(rtcp_sink_pad);
    }
}

GstPadProbeReturn rtcp_sink_buffer_pad_probe_cb(GstPad *pad, GstPadProbeInfo *info, gpointer user_data) {
    GstBuffer *gstBuffer;
    gstBuffer = gst_pad_probe_info_get_buffer(info);
    gboolean result = gst_rtcp_buffer_validate(gstBuffer);
    if (result) {
        //GST_INFO("Pad Probe: RTCP Buffer valid: %d ", result);
        GstRTCPBuffer rtcpBuffer = {NULL,};
        result = gst_rtcp_buffer_map(gstBuffer, GST_MAP_READ, &rtcpBuffer);
        if (result) {
            //GST_INFO("RTCP Buffer valid: %d ", result);
            GstRTCPPacket packet;
            gboolean morePackets;
            morePackets = gst_rtcp_buffer_get_first_packet(&rtcpBuffer, &packet);
            while (morePackets) {
                GstRTCPType type;
				GstRTCPFBType gstRtcpfbType;
                type = gst_rtcp_packet_get_type(&packet);
                switch (type) {
                    case GST_RTCP_TYPE_PSFB:
					    gstRtcpfbType = gst_rtcp_packet_fb_get_type(&packet);
                        switch (gstRtcpfbType) {
                            case GST_RTCP_PSFB_TYPE_FIR:
							    GST_INFO("################# FIR Type found");
                                break;
                            case GST_RTCP_PSFB_TYPE_PLI:
                                GST_INFO("################# PLI Type found");
                                // **Actually here I want to trigger**
                               // **send_key_frame_request_to_sender**
                                break;
                            default:
                                GST_INFO ("Default /Unhandled PSFB FB Type: %d", gstRtcpfbType);
                        }
                        break;
                    case GST_RTCP_TYPE_RTPFB:
                        gstRtcpfbType = gst_rtcp_packet_fb_get_type(&packet);
                        switch (gstRtcpfbType) {
                            default:
                                GST_INFO ("Default /Unhandled RTP FB Type: %d", gstRtcpfbType);
                        }
                        break;
                    default:
                        GST_DEBUG ("Default /Unhandled RTCP Type: %d", type);
                }
                morePackets = gst_rtcp_packet_move_to_next(&packet);
            }
            gst_rtcp_buffer_unmap(&rtcpBuffer);
        }
    }
    return GST_PAD_PROBE_OK;
}
```

But in above switch **case:GST_RTCP_PSFB_TYPE_PLI** is never triggered even though Wireshark shows Chrome-B sends a PLI request.

Please let me know if this is right way to read a PLI from downstream and forward upstream for webrtc video streaming. Does GStreamer-WebRTC has any custom API to do this... or as above standard RTP/RTCP Api's are to be used?

Any suggestions would really help

**Comment by robert-m-taylor** [comment] 2020-05-09 03:55
@sampleref Thank you very much for your post.  I don't have an answer for your problem.  However, using/building on the code you posted, I was able to remove the video degradation problems sufficiently well for my applications (using periodic 10 second key frame pushes with posix threads). 

In case it's helpful to others, just adding the following code to webrtc-sendrecv.c worked great for me for video error resiliency during network packet loss events:

#include <pthread.h>

static void
send_key_frame_request_to_sender() {
  GstPad *videosrcpad;
  videosrcpad = gst_element_get_static_pad(webrtc1, "src_0");
  gst_pad_send_event(videosrcpad, gst_event_new_custom(GST_EVENT_CUSTOM_UPSTREAM,
	 gst_structure_new("GstForceKeyUnit", "all-headers",G_TYPE_BOOLEAN, TRUE, NULL)));
}

void *threadproc(void *arg)
{
    while(1)
    {
        sleep(10);
        send_key_frame_request_to_sender();
    }
    return 0;
}
...
(inside main)
  pthread_t tid;
  pthread_create(&tid, NULL, &threadproc, NULL);
 ...

**Comment by sampleref** [comment] 2020-05-09 08:22
> @sampleref Thank you very much for your post. I don't have an answer for your problem. However, using/building on the code you posted, I was able to remove the video degradation problems sufficiently well for my applications (using periodic 10 second key frame pushes with posix threads).
> 
> In case it's helpful to others, just adding the following code to webrtc-sendrecv.c worked great for me for video error resiliency during network packet loss events:
> 
> #include <pthread.h>
> 
> static void
> send_key_frame_request_to_sender() {
> GstPad *videosrcpad;
> videosrcpad = gst_element_get_static_pad(webrtc1, "src_0");
> gst_pad_send_event(videosrcpad, gst_event_new_custom(GST_EVENT_CUSTOM_UPSTREAM,
> gst_structure_new("GstForceKeyUnit", "all-headers",G_TYPE_BOOLEAN, TRUE, NULL)));
> }
> 
> void *threadproc(void *arg)
> {
> while(1)
> {
> sleep(10);
> send_key_frame_request_to_sender();
> }
> return 0;
> }
> ...
> (inside main)
> pthread_t tid;
> pthread_create(&tid, NULL, &threadproc, NULL);
> ...

I am glad it helped, was just trying to trigger this _send_key_frame_request_to_sender_ on request of PLI/FIR RTCP from downstream webrtc video viewers rather than every defined interval

Hopefully there is way of doing this, will update if something found

**Comment by thaytan** [comment] 2020-05-09 09:21
The RTP session inside webrtcbin should already be translating PLI/FIR into GstForceKeyUnit events in the pipeline. That should show up in the GST_DEBUG=rtpsession:6 logs.

Is the peer sending FIR/PLI?

**Comment by sampleref** [comment] 2020-05-09 13:34
> The RTP session inside webrtcbin should already be translating PLI/FIR into GstForceKeyUnit events in the pipeline. That should show up in the GST_DEBUG=rtpsession:6 logs.
> 
> Is the peer sending FIR/PLI?

Yes the Chrome-B(webrtc)(Reciever) is sending FIR/PLI and I can see that in Wireshark logs too...

With GST_DEBUG=rtpsession:6 I see some logs as below,

> 0:01:55.522155225 [332m    1[00m 0x7f5d8c0030f0 [37mDEBUG  [00m [00m          rtpsession rtpsession.c:2679:rtp_session_request_local_key_unit:[00m Ignoring PLI request from 1 because one was send without one RTT (0:00:00.395002547 < 0:00:00.198898315)
> 0:01:55.715054287 [332m    1[00m 0x7f5d8c0030f0 [33;01mLOG    [00m [00m          rtpsession rtpsession.c:2688:rtp_session_request_local_key_unit:[00m received PLI request from 1 about 55378F4A 0x7f5d96f55290(0x7f5d96f52260)
> 0:01:55.930117152 [332m    1[00m 0x7f5d8c0030f0 [37mDEBUG  [00m [00m          rtpsession rtpsession.c:2679:rtp_session_request_local_key_unit:[00m Ignoring PLI request from 1 because one was send without one RTT (0:00:00.215058483 < 0:00:00.218856811)
> 0:01:56.119330878 [332m    1[00m 0x7f5d8c0030f0 [33;01mLOG    [00m [00m          rtpsession rtpsession.c:2688:rtp_session_request_local_key_unit:[00m received PLI request from 1 about 55378F4A 0x7f5d96f55290(0x7f5d96f52260)
> 0:02:25.463819955 [332m    1[00m 0x7f5d8c0030f0 [37mDEBUG  [00m [00m          rtpsession rtpsession.c:2679:rtp_session_request_local_key_unit:[00m Ignoring PLI request from 1 because one was send without one RTT (0:00:00.198847830 < 0:00:00.188583374)
> 0:02:25.661805868 [332m    1[00m 0x7f5d8c0030f0 [33;01mLOG    [00m [00m          rtpsession rtpsession.c:2688:rtp_session_request_local_key_unit:[00m received PLI request from 1 about 55378F4A 0x7f5d96f55290(0x7f5d96f52260)

But Chrome-A(webrtc)(Sender)  is not receiving it, unless I send using GstForceKeyUnit at regular intervals... 

And also is the above approach correct to read/get notified of RTCP FIR/PLI requests via rtpbin?

**Comment by thaytan** [comment] 2020-05-10 12:42
Ah, I see. In the case where GStreamer is the receiver, the problem is related to https://gitlab.freedesktop.org/gstreamer/gst-plugins-good/-/merge_requests/455

**Comment by sampleref** [comment] 2020-05-10 21:19
> Ah, I see. In the case where GStreamer is the receiver, the problem is related to https://gitlab.freedesktop.org/gstreamer/gst-plugins-good/-/merge_requests/455

Ok Thanks for pointing to it, 
But until its merged or stable fix is available, can you please suggest what is the appropriate way to get hold of _RTPSession_ from _rtpbin_ and connect to signals **on-sending-rtcp** and **on-receiving-rtcp**  signals, so I can trigger PLI/FIR to Sender peer accordingly

Are the signals/callbacks `on-new-ssrc/get-storage` on rtpbin right to get hold of RTPSession with `g_signal_emit_by_name(rtpbin, "get-internal-session", 0, &session); `

Most of the examples I see pass **0** as argument for _session id_ but is it same _session Id_ received on callback signals of `on-new-ssrc/get-storage`?

**Comment by thaytan** [comment] 2020-05-15 17:38
I think what I would be doing is putting an event pad probe on the source pad from webrtcbin and looking for the packet lost messages from the rtp jitterbuffer for the stream. That will let you generate a force keyframe event in the way that the depayloader will hopefully do in the future.

**Comment by ystreet** [comment] 2021-04-28 09:06
Various video payloaders can produce automatic keyframe requests when they receive packet loss with GStreamer 1.20+.  Others can be added as needed.  This is a GStreamer issue though and not an issue with these examples/demos.

These examples have moved to https://gitlab.freedesktop.org/gstreamer/gst-examples/-/tree/master/webrtc and this repository will not be updated further.

**Closed as completed by ystreet** 2021-04-28 09:06 UTC
